### ISSUE TITLE
UC09: User Exits Work Agreement

### ISSUE THREAD

**Issue by ssfaron** [ronwellman/CSI5324_Group_Project#8]
The User (Consumer or Freelancer) navigates to the Service Listing page and selects the ”Terminate Contract” button associated with the service under agreement. The system prompts the User to confirm that they would like to terminate the contract for the specified service. The User selects the ”Yes Terminate Contract” button. The system notifies both parties (Consumer and Freelancer) that the contract has been terminated.

**Comment by ronwellman** [comment]
Already Completed.
